# Generated by Django 5.1 on 2025-10-03 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachments', models.JSONField(default=list)),
                ('headers', models.JSONField(default=dict)),
                ('headerLines', models.JSONField(default=list)),
                ('html', models.TextField(blank=True)),
                ('text', models.TextField(blank=True)),
                ('textAsHtml', models.TextField(blank=True)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('to', models.JSONField(default=dict)),
                ('from_field', models.JSONField(default=dict)),
                ('messageId', models.CharField(blank=True, max_length=255)),
                ('raw', models.TextField(blank=True)),
                ('dkim', models.JSONField(default=dict)),
                ('spf', models.JSONField(default=dict)),
                ('arc', models.JSONField(default=dict)),
                ('dmarc', models.JSONField(default=dict)),
                ('bimi', models.JSONField(default=dict)),
                ('recipients', models.JSONField(default=list)),
                ('session', models.JSONField(default=dict)),
            ],
        ),
    ]
