runtime: python311
entrypoint: gunicorn -b :$PORT spamlibs_project.wsgi

env_variables:
  DJANGO_DEBUG: False

handlers:
- url: /static
  static_dir: static/
- url: /.*
  script: auto
  secure: always
